name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  

    env:
      Solution_Name: DonkeyWork.Dev.SimpleRateLimiter.sln       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: "./Test/DonkeyWork.Dev.SimpleRateLimiter.Tests/DonkeyWork.Dev.SimpleRateLimiter.Tests.csproj"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Solution
      run: dotnet build

    - name: Execute unit tests
      run: dotnet test
